# More info: https://jupyterbook.org/customize/config.html.

#######################################################################################
# Book settings
title: {{ cookiecutter.book_name }}
author: {{ cookiecutter.author_name }}
copyright: "{% now 'local', '%Y' %}"

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  favicon: "favicon.svg"
