# More info: https://jupyterbook.org/customize/config.html.

#######################################################################################
# Book settings
title: {{ cookiecutter.book_name }}
author: {{ cookiecutter.author_name }}
copyright: "{% now 'local', '%Y' %}"

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  favicon: "favicon.svg"

#######################################################################################
# Advanced and power-user settings
sphinx:
  config:
    html_theme_options:
      search_bar_text: "Search"
